In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('data/movie_ratings.csv')

In [5]:
data.head(10)

   rating_id      movie_title  user_id  rating rating_date  review_length
0          1       The Matrix      333     3.4  2025-09-09            335
1          2     Pulp Fiction      773     4.3  2025-08-22            411
2          3       Fight Club      238     4.3  2025-11-04            246
3          4       The Matrix      273     3.4  2025-06-02             30
4          5     Interstellar      286     2.3  2025-05-16             18
5          6       Fight Club      423     4.6  2025-05-18            268
6          7        Inception      321     4.2  2025-02-08             12
7          8  The Dark Knight      812     3.1  2025-05-28            139
8          9        Inception      588     3.5  2025-07-18            264
9         10        Inception      899     4.8  2025-08-03            130

In [6]:
data.dtypes

rating_id          int64
movie_title          str
user_id            int64
rating           float64
rating_date          str
review_length      int64
dtype: object

In [7]:
data.describe()

         rating_id       user_id        rating  review_length
count  10000.00000  10000.000000  10000.000000   10000.000000
mean    5000.50000    501.771200      2.999970     252.177400
std     2886.89568    288.212132      1.145771     145.078236
min        1.00000      1.000000      1.000000       0.000000
25%     2500.75000    255.000000      2.000000     127.000000
50%     5000.50000    500.000000      3.000000     253.000000
75%     7500.25000    748.000000      4.000000     378.000000
max    10000.00000   1000.000000      5.000000     500.000000

In [10]:
data.groupby(['movie_title']).agg('count')

                 rating_id  user_id  rating  rating_date  review_length
movie_title
Fight Club            1228     1228    1228         1228           1228
Forrest Gump          1270     1270    1270         1270           1270
Inception             1272     1272    1272         1272           1272
Interstellar          1235     1235    1235         1235           1235
Pulp Fiction          1230     1230    1230         1230           1230
The Dark Knight       1270     1270    1270         1270           1270
The Godfather         1237     1237    1237         1237           1237
The Matrix            1258     1258    1258         1258           1258

In [11]:
data.groupby('rating').agg('count')

        rating_id  movie_title  user_id  rating_date  review_length
rating
1.0           121          121      121          121            121
1.1           238          238      238          238            238
1.2           236          236      236          236            236
1.3           263          263      263          263            263
1.4           244          244      244          244            244
1.5           237          237      237          237            237
1.6           251          251      251          251            251
1.7           268          268      268          268            268
1.8           227          227      227          227            227
1.9           253          253      253          253            253
2.0           258          258      258          258            258
2.1           263          263      263          263            263
2.2           238          238      238          238            238
2.3           247          247      247          247            247
2.4           244          244      244          244            244
2.5           255          255      255          255            255
2.6           244          244      244          244            244
2.7           238          238      238          238            238
2.8           279          279      279          279            279
2.9           257          257      257          257            257
3.0           236          236      236          236            236
3.1           266          266      266          266            266
3.2           274          274      274          274            274
3.3           263          263      263          263            263
3.4           273          273      273          273            273
3.5           248          248      248          248            248
3.6           248          248      248          248            248
3.7           236          236      236          236            236
3.8           255          255      255          255            255
3.9           230          230      230          230            230
4.0           283          283      283          283            283
4.1           260          260      260          260            260
4.2           239          239      239          239            239
4.3           252          252      252          252            252
4.4           249          249      249          249            249
4.5           239          239      239          239            239
4.6           230          230      230          230            230
4.7           254          254      254          254            254
4.8           233          233      233          233            233
4.9           256          256      256          256            256
5.0           115          115      115          115            115